#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_INIT_WINDOW_WIDTH 800
#define CONFIG_INIT_WINDOW_HEIGTH 600

#define CONFIG_MIN_WINDOW_WIDTH 700
#define CONFIG_MIN_WINDOW_Height 400

#define DEBUG

#endif