name: Build and Test (MSYS2 / MinGW)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      # --- Checkout ---
      - uses: actions/checkout@v4

      # --- MSYS2 Setup with caching ---
      - name: Set up MSYS2 with MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gdb
          cache: true

      # --- Verify MSYS2 installation ---
      - name: Verify MSYS2 packages
        shell: msys2 {0}
        run: pacman -Q mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-gdb

      # --- Add MinGW64 to Windows PATH ---
      - name: Add MinGW64 to PATH
        shell: cmd
        run: set "PATH=%PATH%;C:\msys64\mingw64\bin"

      # --- Debug Windows environment ---
      - name: Debug environment
        shell: cmd
        run: |
          echo PATH=%PATH%
          where gcc
          where mingw32-make
          mingw32-make --version
          gcc --version

      # --- Ensure artifacts and build directories exist ---
      - name: Prepare directories
        shell: cmd
        run: |
          if not exist artifacts mkdir artifacts
          if not exist artifacts\builds mkdir artifacts\builds
          if not exist artifacts\logs mkdir artifacts\logs
          if not exist build mkdir build
          if not exist build\main mkdir build\main
          if not exist build\main\components mkdir build\main\components
          if not exist build\main\core mkdir build\main\core
          if not exist build\main\utils mkdir build\main\utils
          if not exist build\main\demo mkdir build\main\demo

      # --- Debug Makefile variables ---
      - name: Debug Makefile variables
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe DEMO=narcia MODE=release -n
          mingw32-make SHELL=cmd.exe DEMO=calendar MODE=release -n

      # --- Unit Test ---
      - name: Clean before unit test
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build and run unit tests
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe test > artifacts\logs\test_output.txt
          dir build

      # --- Narcia Build ---
      - name: Clean before Narcia build
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build Narcia (Release)
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe DEMO=narcia MODE=release
          dir build
          if exist build\my_program.exe (copy build\my_program.exe artifacts\builds\narcia.exe) else (echo ERROR: my_program.exe not found in build directory && exit /b 1)

      # --- Calendar Build ---
      - name: Clean before Calendar build
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build Calendar (Release)
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe DEMO=calendar MODE=release
          dir build
          if exist build\my_program.exe (copy build\my_program.exe artifacts\builds\calendar.exe) else (echo ERROR: my_program.exe not found in build directory && exit /b 1)

      # --- Summarize Test Results and Artifacts ---
      - name: Summarize test results and artifacts
        shell: cmd
        run: |
          echo Test Log Summary:
          type artifacts\logs\test_output.txt
          echo.
          echo Artifact List:
          dir artifacts\builds
          dir artifacts\logs
          echo.
          echo ## Test Results and Artifacts > $GITHUB_STEP_SUMMARY
          echo ### Test Log >> $GITHUB_STEP_SUMMARY
          type artifacts\logs\test_output.txt >> $GITHUB_STEP_SUMMARY
          echo. >> $GITHUB_STEP_SUMMARY
          echo ### Artifacts >> $GITHUB_STEP_SUMMARY
          dir artifacts\builds >> $GITHUB_STEP_SUMMARY
          echo. >> $GITHUB_STEP_SUMMARY
          echo ### Test Summary >> $GITHUB_STEP_SUMMARY
          findstr /C:"passed" /C:"failed" artifacts\logs\test_output.txt >> $GITHUB_STEP_SUMMARY || echo No pass/fail summary found in test_output.txt >> $GITHUB_STEP_SUMMARY

      # --- Upload Artifacts ---
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: artifacts/logs/test_output.txt
          retention-days: 7

      - name: Upload release builds
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: |
            artifacts/builds/narcia.exe
            artifacts/builds/calendar.exe
          retention-days: 7

      # --- Optional: Create GitHub Release (uncomment to enable) ---
      # - name: Create GitHub Release
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       artifacts/builds/narcia.exe
      #       artifacts/builds/calendar.exe
      #       artifacts/logs/test_output.txt
      #     name: Release ${{ github.ref_name }}
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}