name: Build and Test (MSYS2 / MinGW)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      # --- Checkout ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- MSYS2 Setup ---
      - name: Set up MSYS2 with MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gdb
          cache: false

      # --- Verify Installation ---
      - name: Verify MSYS2 packages
        shell: msys2 {0}
        run: |
          pacman -Q mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-gdb

      # --- Add MinGW64 to Windows PATH ---
      - name: Add MSYS2 MinGW64 to PATH
        shell: cmd
        run: |
          set "PATH=%PATH%;C:\msys64\mingw64\bin"

      - name: Debug Windows environment
        shell: cmd
        run: |
          echo PATH=%PATH%
          where mingw32-make
          mingw32-make --version

      # --- Ensure artifacts folder exists ---
      - name: Create artifacts directory
        shell: cmd
        run: |
          if not exist artifacts mkdir artifacts

      # --- Unit Test ---
      - name: Clean before unit test
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build and run unit tests
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe test > artifacts\test_output.txt

      # --- Narcia Build ---
      - name: Clean before Narcia build
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build Narcia (Release)
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe DEMO=narcia MODE=release
          copy build\narcia.exe artifacts\

      # --- Calendar Build ---
      - name: Clean before Calendar build
        shell: cmd
        run: mingw32-make SHELL=cmd.exe clean --debug

      - name: Build Calendar (Release)
        shell: cmd
        run: |
          mingw32-make SHELL=cmd.exe DEMO=calendar MODE=release
          copy build\calendar.exe artifacts\

      # --- Upload Artifacts ---
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: artifacts/test_output.txt
          retention-days: 7

      - name: Upload release builds
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: |
            artifacts/narcia.exe
            artifacts/calendar.exe
          retention-days: 7
