name: Build and Test (MSYS2 / MinGW)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2 with MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gdb
          cache: true

      - name: Debug MSYS2 environment
        shell: msys2 {0}
        run: |
          echo "MSYS2 Environment Info:"
          echo "MSYSTEM: $MSYSTEM"
          echo "PATH: $PATH"
          which make
          which mingw32-make

      - name: Create artifacts directory
        shell: cmd
        run: |
          if not exist artifacts mkdir artifacts

      # --- Unit Test ---
      - name: Clean before unit test
        shell: msys2 {0}
        run: mingw32-make clean

      - name: Build and run unit tests
        shell: msys2 {0}
        run: |
          mingw32-make test > artifacts/test_output.txt

      # --- Narcia Build ---
      - name: Clean before Narcia build
        shell: msys2 {0}
        run: mingw32-make clean

      - name: Build Narcia (Release)
        shell: msys2 {0}
        run: |
          mingw32-make DEMO=narcia MODE=release
          cp build/narcia.exe artifacts/

      # --- Calendar Build ---
      - name: Clean before Calendar build
        shell: msys2 {0}
        run: mingw32-make clean

      - name: Build Calendar (Release)
        shell: msys2 {0}
        run: |
          mingw32-make DEMO=calendar MODE=release
          cp build/calendar.exe artifacts/

      # --- Upload Artifacts ---
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: artifacts/test_output.txt
          retention-days: 7

      - name: Upload release builds
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: |
            artifacts/narcia.exe
            artifacts/calendar.exe
          retention-days: 7